name: DiffMethylTools
channels:
  - r
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - scipy=1.13.1=py312h2809609_0
  - pandas=2.2.2=py312h526ad5a_0
  - numpy=1.26.4=py312h2809609_0
  - statsmodels=0.14.2=py312ha883a20_0
  - polars=1.6.0=py312h1b14708_0
  - matplotlib=3.9.2=py312h7900ff3_0
  - seaborn=0.13.2=py312h06a4308_0
  - rpy2=3.5.11=py312r43hc7c0aa3_3
  - bioconductor-limma=3.58.1=r43ha9d7317_1
  - pyarrow=11
  - ncurses=6.5
  - statsmodels=0.14.2
  - seaborn=0.13.2
  - minimap2=2.1.1
  - htslib=1.20
  - pip
  - pip:
    - joblib
